# Generated by Django 4.2.5 on 2023-09-24 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_subject_tests_alter_classrooms_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TG_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(unique=True)),
                ('phone', models.CharField(max_length=50, unique=True, verbose_name='Phone')),
                ('username', models.CharField(max_length=128)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('log', models.JSONField(default={'state': 0})),
                ('lang', models.CharField(choices=[('uz', 'uz'), ('ru', 'ru'), ('en', 'en')], default='uz', max_length=2)),
                ('ut', models.SmallIntegerField(choices=[(1, 'Admin'), (2, 'Teacher'), (3, 'User')], default=3, verbose_name='User Type')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.classrooms')),
            ],
            options={
                'verbose_name_plural': '0. TG_Users',
            },
        ),
    ]
