# Generated by Django 4.2.5 on 2023-10-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tg_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tg_user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
