# Generated by Django 4.2.5 on 2023-10-14 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tg_user_is_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tests',
            options={'verbose_name_plural': 'T. Test'},
        ),
        migrations.RemoveField(
            model_name='tests',
            name='ball',
        ),
        migrations.RemoveField(
            model_name='tests',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='tests',
            name='img',
        ),
        migrations.RemoveField(
            model_name='tests',
            name='subject',
        ),
        migrations.AlterField(
            model_name='tests',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='tests',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='tests',
            name='updated',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1028)),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('desc', models.TextField(blank=True, null=True)),
                ('ball', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tests')),
            ],
            options={
                'verbose_name_plural': '4. Tests',
            },
        ),
        migrations.AlterField(
            model_name='completedtest',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.quiz'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.quiz'),
        ),
    ]
