# Generated by Django 4.2.5 on 2023-10-14 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_is_active_user_is_admin_user_is_staff_user_log_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.BigIntegerField(null=True, verbose_name='TG_User_ID'),
        ),
    ]
