# Generated by Django 4.2.5 on 2023-10-15 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_tests_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='tests',
            name='timeout',
            field=models.IntegerField(default=5, verbose_name='Testlarni ishlashga beriladigan vaqt'),
        ),
    ]
